name: first demo 
on:
 push:
  branches: 
  - main 
jobs:
  demo_job:
   runs-on: ip-172-31-39-102
   steps:
    - uses: actions/checkout@v3
    - name: run a one-line script
      run: sh ./demo.sh
    - name: run multiple-line script
      run: | 
          echo Nothing to show here.. ...............
          echo what is java ?
          ls -a
